### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by furtabs** [lazyMods/exnihilo-automation#1]
remade it all from scratch. Font is Benguin
![Logo](https://user-images.githubusercontent.com/48419040/110260426-2fd29680-7f7a-11eb-856d-d0eabcbfe2ba.png)

**Comment by lazynessmind** [comment]
oh, thanks! do you any page or site to put in the credits?

**Comment by furtabs** [comment]
All yours

**Comment by lazynessmind** [comment]
Oh, thanks. I really appreciate it.
But I'm gonna put your Github in the Readme.
