### ISSUE TITLE
More input and output face.

### ISSUE THREAD

**Issue by liuseniubi** [lazyMods/exnihilo-automation#12]
Only one input and output face is not that convenient for automation.
And another little problem.
These text in the GUI (like Auto Silker) can't be localized.
![image](https://user-images.githubusercontent.com/67419568/111944430-96c38400-8b12-11eb-8b9e-4f9b96e91597.png)

**Comment by lazynessmind** [comment]
Working on it! Thanks for the feedback.

**Comment by lazynessmind** [comment]
Fixed in 24b6077 and a1f7a81

**Comment by liuseniubi** [comment]
Thank a lot!
