### ISSUE TITLE
ExAuto will not load after ExSeq Update

### ISSUE THREAD

**Issue by papaworld** [lazyMods/exnihilo-automation#16]
Hi,

"Error loading mods"
exnihiloauto requires exnihiloseqentia 1.16-2.0.2.3
currently exnihilosequentia is 1.16-2.0.2.5

FML: 36.1.4
exnihiloauto 1.16-1.0.3.0 

Thank you.

**Comment by kreezxil** [comment]
Ditto, I woujld like to use the latest builds of exnihilo, but I can't because this mod won't accept it.

**Comment by Irgendwer01** [comment]
@papaworld @kreezxil I have made a PR for updating Sequentia #18

**Comment by kreezxil** [comment]
@papaworld @Irgendwer01 Got tired of waiting for a release to fix minor issues. Used Irgendwer01's builds to create and get released https://www.curseforge.com/minecraft/mc-mods/exnihilo-automation-unstable

**Comment by lazynessmind** [comment]
@kreezxil I already updated it the mod
Just check the curse page ihih

**Comment by lazynessmind** [comment]
Fixed in 43c481c and 5e87f71.

**Comment by papaworld** [comment]
Thank you for updating... kewl mod. Hats-off to ya!

**Comment by lazynessmind** [comment]
@papaworld thanks... If you have any suggestions, feel free to share
