### ISSUE TITLE
excessive spam in console

### ISSUE THREAD

**Issue by kreezxil** [lazyMods/exnihilo-automation#17]
It prints FALSE constantly on a dedicated server, this appears to be a hold-over from your debug. Need a config to disable it.

debug.log: https://gist.github.com/54879d889decb47da2a45a6ad2ae0425
latest.log: https://gist.github.com/f715500ff79b2f475dbd6c52ea0a43ff

1.16-1.0.3.0 on Forge 36.1.6

**Comment by kreezxil** [comment]
resolved via the alternative: https://www.curseforge.com/minecraft/mc-mods/exnihilo-automation-unstable, still not resolved in this mod, but I'll close it anyways.

**Comment by lazynessmind** [comment]
Didn´t find anything being printed on the console. 
You are probably talking about this one 23f1cf9.
I think that I fixed the spam but didn't release a version with the fix to curse, let me know if you find the spam in the new version 1.1.0.0 https://www.curseforge.com/minecraft/mc-mods/exnihilo-automation/files/3297219
