### ISSUE TITLE
Silker crashes - (ExNihilo Sequentia 2.0.2.7/8)

### ISSUE THREAD

**Issue by zpprsprk** [lazyMods/exnihilo-automation#20]
https://gist.github.com/zpprsprk/a4ff8526296e6bddf9a0ff1c118f2db1

Whether adding by shift-click or by placing it in, both in single player and on a server.

**Comment by lazynessmind** [comment]
Looking into it. Thanks

**Comment by lazynessmind** [comment]
After looking the given gist, it seems that it doesn't have anything related to this mod. It seems ex compressum is making it crash when looking into hammer recipes.

**Comment by zpprsprk** [comment]
So is this an incompatability with ex compressum then? I understand there is an overlap between the mods, but there are features of each that are not in the other and it would be nice to be able to use both...

**Comment by lazynessmind** [comment]
I couldn't find the real reason why the crash was happening in your gist, and it's actually ex nihilo auto fault. Fixing it. Sorry

Reason: Ex Nihilo Sequentia changed internally and broke on .7 and .8 versions

**Comment by lazynessmind** [comment]
https://www.curseforge.com/minecraft/mc-mods/exnihilo-automation

fix in the latest version.
