### ISSUE TITLE
Bonus Drop Upgrade cannot add to Automatic Sieve

### ISSUE THREAD

**Issue by olbb** [lazyMods/exnihilo-automation#21]
The Bonus Drop Upgrade  can only add to Automatic Hammer, but can't dd to Automatic Sieve.
Please fix it, many thanks.
Game version is exnihiloauto-1.16-1.2.0.0.jar which is upload on 6/22

**Comment by lazynessmind** [comment]
> The Bonus Drop Upgrade can only add to Automatic Hammer, but can't dd to Automatic Sieve.

That's not a bug. You can't add bonus upgrades to Auto Sieves because you can get better drops by crafting better meshes. 

![image](https://user-images.githubusercontent.com/52864251/123153177-4cc5a380-d45d-11eb-9ebe-9b6034b1e196.png)

**Comment by olbb** [comment]
Okay, it seems like a bug made by zh_cn translation.
![image](https://user-images.githubusercontent.com/5554102/123202633-d24f5080-d469-11eb-9bd4-989a9def1dd2.png)
