### ISSUE TITLE
Items disappearing or adding empty NBT tags from automatic sieve ex nihilo automation

### ISSUE THREAD

**Issue by LWLegends** [lazyMods/exnihilo-automation#25]
Meshes and all items in the sieve disappear when logging.  While sieving items, if you shift click them out of the Sieve, they appear to have empty NBT tags and will not stack with other of the same items.  However, dragging them manually out, they are fine.

  [https://www.youtube.com/watch?v=qolMYO4GuKI&t=3s](url)

**Comment by ChuckFaulker** [comment]
It actually happens inside of the sieve, whether you touch the items or not.

https://youtu.be/qolMYO4GuKI

**Comment by lazynessmind** [comment]
Hi! Thanks for letting me know.
Working on it.
And sorry for the late reply, but for some reason I didn't receive any notification.

**Comment by lazynessmind** [comment]
> Meshes and all items in the sieve disappear when logging. ~

This one is fixed.

> While sieving items, if you shift-click them out of the Sieve, they appear to have empty NBT tags and will not stack with other of the same items. However, dragging them manually out, they are fine.

This one I can't replicate it on my end. Investigating it...

**Comment by lazynessmind** [comment]
I'm waiting on a response, and I'm releasing a version with a patch that fixes machines not saving the Items correctly.

**Comment by lazynessmind** [comment]
Closing and pinning this issue.
