### ISSUE TITLE
compressed block wrong drop

### ISSUE THREAD

**Issue by hunikyel71** [lazyMods/exnihilo-automation#26]
hello, i don t know if it come from your mod but when i use renforced hammer on compressed block (ex : compressed cobblestone) the drops are x9 vanilla cobblestones, and it the same for all compressed block by hand or in the auto hammer.

 minecraft 1.16.5

exnihiloauto-1.16-1.2.0.1

**Comment by lazynessmind** [comment]
probably it's from my mod
thanks for letting me know

**Comment by marcosantos98** [comment]
Fixed in upcomming version
