### ISSUE TITLE
Auto Hammer not working properly

### ISSUE THREAD

**Issue by Enevoado** [lazyMods/exnihilo-automation#29]
If I put a Compresed Cobblestone in the Auto Hammer it outputs one single couble, if I put a Highly Compressed Cobblestone it outputs one Compressed Cobblestone, and so on.

The bahaviour I expect is: if a put one Compressed Cobblestone it outpus one Compressed Gravel, and so on.

**Comment by marcosantos98** [comment]
It is fixed in an upcoming version.
