### ISSUE TITLE
Could you make a 1.16.4 version?

### ISSUE THREAD

**Issue by LokutusPokutus** [lazyMods/exnihilo-automation#3]
I just saw that it's for 1.16.5 and I was wondering if it works with 1.16.4 or if it doesn't.

**Comment by lazynessmind** [comment]
I can make a 1.16.4 build since nothing changes between the versions, but why you want to use the 1.16.4?

**Comment by LokutusPokutus** [comment]
I'm playing a modpack and I like to add mods I like and it's in 1.16.4

**Comment by lazynessmind** [comment]
That's a good reason. Uploading to curse! Have a good weekend.

**Comment by lazynessmind** [comment]
Nevermind. Just download the 1.0.1.3 that supports 1.16.4/5
