### ISSUE TITLE
Missing Dust

### ISSUE THREAD

**Issue by CaptJack2883** [lazyMods/exnihilo-automation#4]
I recently downloaded your mod for a custom modpack that I made. With the newest versions 1.0.1.0 and 1.0.1.1 I get an error message talking about exnihilosequentia:dust and exnihiloauto:compressed_dust Registry Objects not present. 
If I go back to version 1.0.0.0 the issue disappears.  I will upload my error log and a screenshot if I am able. 
I am currently using Forge 36.0.54, but I was also getting the same error with Forge 36.0.46
My Ex Nihilo Sequentia version is 2.0.2.3

[crash-2021-03-12_02.57.08-fml.txt](https://github.com/lazyMods/ExNihiloAutomation/files/6128812/crash-2021-03-12_02.57.08-fml.txt)

![ex nihilo auto error](https://user-images.githubusercontent.com/59985652/110917326-68a69e80-82df-11eb-849b-7dd109b6378f.jpg)

**Comment by lazynessmind** [comment]
Thanks for your feedback. An update with the fix was uploaded to Curse. Have a good weekend.
